"""Core domain objects for AutoAgent — CI/CD for agents.

First-class objects: AgentGraphVersion, SkillVersion, ToolContractVersion,
PolicyPackVersion, EnvironmentSnapshot, GraderBundle, EvalCase,
CandidateVariant, ArchiveEntry, HandoffArtifact.
"""

from core.types import (
    AgentNodeType,
    AgentNode,
    EdgeType,
    AgentEdge,
    AgentGraphVersion,
    SkillVersion,
    ReplayMode,
    ToolContractVersion,
    PolicyPackVersion,
    EnvironmentSnapshot,
    SnapshotDiff,
    GraderType,
    GraderSpec,
    GraderBundle,
    EvalCase,
    EvalSuiteType,
    CandidateVariant,
    ArchiveRole,
    ArchiveEntry,
    JudgeVerdict,
    MetricLayer,
    LayeredMetric,
)
from core.eval_model import (
    Annotation,
    Dataset,
    Evaluation,
    EvaluationRun,
    Grader,
    GraderKind,
    GraderResult,
    RunResult,
)
from core.handoff import HandoffArtifact, HandoffComparator

__all__ = [
    "AgentNodeType",
    "AgentNode",
    "EdgeType",
    "AgentEdge",
    "AgentGraphVersion",
    "SkillVersion",
    "ReplayMode",
    "ToolContractVersion",
    "PolicyPackVersion",
    "EnvironmentSnapshot",
    "SnapshotDiff",
    "GraderType",
    "GraderSpec",
    "GraderBundle",
    "EvalCase",
    "EvalSuiteType",
    "CandidateVariant",
    "ArchiveRole",
    "ArchiveEntry",
    "JudgeVerdict",
    "MetricLayer",
    "LayeredMetric",
    "Annotation",
    "Dataset",
    "Evaluation",
    "EvaluationRun",
    "Grader",
    "GraderKind",
    "GraderResult",
    "RunResult",
    "HandoffArtifact",
    "HandoffComparator",
]
